# Generated by Django 3.1.2 on 2020-11-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_candy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.store'),
        ),
    ]
