# Generated by Django 3.1.2 on 2020-11-01 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201101_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.store'),
        ),
    ]
