# Generated by Django 3.1.2 on 2020-11-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201101_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.store'),
            preserve_default=False,
        ),
    ]
