# Generated by Django 3.1.2 on 2020-11-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201101_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Buyer',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='store',
            name='buyer',
            field=models.ManyToManyField(to='main_app.Buyer'),
        ),
    ]
