# Generated by Django 3.1.2 on 2020-11-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201102_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
