# Generated by Django 3.1.2 on 2020-11-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_buyer_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='buyer',
            new_name='buyers',
        ),
    ]
